[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "homework-packer"
version = "0.1.0"
description = "A tool to pack student assignments."
dependencies = [
    "pandas == 2.3.3",
    "openpyxl == 3.1.5",
]
